### PR TITLE
Migration to .NET Standard 2.0

### PR DESCRIPTION
**Pull request by ktos**
The package now supports .NET Standard 2.0, so it is available for Xamarin, Unity, UWP, etc. (and is not showing errors in .NET 5 or later anymore).

### CODE REVIEW

**Comment by ktos** [comment]
Zamiast Nuget.Build.Packaging teraz buduje się paczkę używając standardowego polecenia w .NET 5 - po prostu `dotnet pack` i dostajesz `.nupkg`.

**Comment by Mondonno** [comment]
@ktos i saw that you migrated the files from `Airly.Net/contents/*` to `Airly.Net/*` why? Also what's changing with deleting the assembly info file and why you deleted it? All other things looks very good 👍

**Review by Mondonno — CHANGES_REQUESTED** [review]
Please explain deletion of `AssemblyInfo.cs`, `packages.config`, also visual studio have some realy strange things when the test imported project does not depend on the same packages as the main project. Also explain the migration as i mentioned above. As I said above all other things look good 💯

**Comment by ktos** [comment]
* `packages.config` is not needed anymore, in new project system dependencies are in the `.csproj` file,
* `AssemblyInfo.cs` was empty (identical to the default one), do you still need it? We can revert it, no problem,
* Moving from `content/` - I thought you moved everything to `content/` to avoid source code merging with project configuration (e.g. `packages.config`). I think we can move it back, it does not matter actually,
* `dotnet test` had no problems after removing dependency - I've not tested on VS for Mac; it can be reverted, but the dependent version must be the same (13.0.0.2) as the original version (and was something like 12.0.0.0 and it conflicted).

**Review by Mondonno — APPROVED** [review]
All unit-tests passed on my side 👍 
So i think i'm able to merge this PR #1

**Pull request merged**
